version: '3.2'
services:
    mongoDb:
        image: mongo
        ports:
        - "27017:27017"
    web:
        build: ./frontend
        ports:
        - "3000:3000"
        volumes:
        - ./frontend/src:/frontend/src:rw
    searchroomservice:
        build: ./service-searchRoom
        ports:
        - "8091:8091"
    rentroomservice:
        build: ./service-rentRoom
        ports:
        - "8092:8092"
    uploadpaymentservice:
        build: ./service-uploadPayment
        ports:
        - "8093:8093"